### PR TITLE
Add more layers

### PR DESCRIPTION
**Pull request by orangejulius**
@dianashk noticed that records with the `PPL` [feature code](http://www.geonames.org/export/codes.html) probably map best to our `localadmin` layer. I also noticed that `PPLA` and `PPLA2` definitely map to `locality` (`PPLA` includes cities like Boise, ID). I'm not sure about PPL3 yet.

### CODE REVIEW

**Comment by missinglink** [comment]
@thisisaaronland might have a mapping file between geonames feature codes and WOF?

**Comment by dianashk** [comment]
FYI Chelsea NY is also a `PPL`

```
5112386	Chelsea	Chelsea		41.5537	-73.96681	P	PPL	US		NY	027			0	12	18	America/New_York	2006-01-15
5112387	Chelsea	Chelsea		40.60066	-74.19487	P	PPL	US		NY	085			0	2	2	America/New_York	2006-01-15
```

**Comment by orangejulius** [comment]
After further review we've determined we have to look at every feature code that was mapped to an admin category in the old category mapping. Here's the results

- [ ] PPLA2: should be`locality`
- [ ] PPLA3: should probably be `locality`
- [ ] PPLA4: probably `locality`
- [ ] LCTY: geonames locality. Does not seem to map to our localities (it does contain lots of amusement park rides! :roller_coaster: )
- [ ] ZN: zone. corresponds to large, multi-state regions in the US. not particularly interesting and should probably be filtered out
- [ ] ADM3H: historical admin regions, should be filtered out
- [ ] ADMD: townships. was already handled as locality
- [ ] PPLR: religious populated places. this could probably be localadmin
- [ ] ZNB: buffer zones. only 4 records in the world
- [ ] LTER: leased areas. fine to stay as venues
- [ ] ADM4H: historical admin areas. we should probably filter these out
- [ ] ADM4: these appear to be neighborhoods, for example [Montréal-Nord](https://en.wikipedia.org/wiki/Montr%C3%A9al-Nord)
- [ ] ADM5: definitely neighborhoods
- [ ] ADM1: region
- [ ] ADM2: county
- [ ] ADM3: not sure, but in germany they correspond to Kreis (districts) that are something in between states and counties. see https://en.wikipedia.org/wiki/Thuringia for an example
- [ ] PPLA: cities. in the US they correspond to state capitals
- [ ] PPLC: country capitals
- [ ] PPLF: farm village. I've put them in `localadmin` like `PPL`
- [ ] PPLG: seats of governments like The Hague. Definitely `locality`
- [ ] PPLL: populated locality (includes woodstock!) I think these are `localadmin`s at best
- [ ] PPLQ: abandoned places. we should filter these out as all the titles contain "(Historical)"
- [ ] PPLS: populated places. In the US it appears to be all Census Designated Places
- [ ] PPLW: destroyed places. we should filter these out
- [ ] PPLX: section of populated place. Definitely neighborhoods. Includes Gowanus!!!
- [ ] ADM1H: historical admin areas. Includes Britannia so if we ever make a geocoder for the Roman empire, we can add these. For now we should filter them out
- [ ] PPLCH: historical capitals. There are only two and we should filter them out.
- [ ] PPL: already mapped to `localadmin`
- [ ] TERR: territories, like American Samoa. I've put them as `region`s
- [ ] CONT: continents. exactly what you'd expect. Should we add a continent type? Filter them out?
- [ ] STLMT: Israeli settlements. I think these most closely map to neighborhoods
- [ ] RGNE: Economic region. We definitely want to filter these out. See #42 
- [ ] ADM2H: historical admin areas. we should filter them out
- [ ] ADMDH: same

**Comment by dianashk** [comment]
:ship:

**Comment by orangejulius** [comment]
I added one more mapping, for country! (`PCLI`)

**Comment by hannesj** [comment]
The division between `locality` and `localadmin` seems a bit strange if you compare it to how whosonfirst [defines them](https://github.com/whosonfirst/whosonfirst-placetypes/blob/master/README.md#localadmin). Especially the part about localadmin consisting of multiple localities in wof, which seems to be the inverse of how this pr seems to handle them.

**Comment by orangejulius** [comment]
Shoot, you're totally right. Turns out I my mental model of them was reversed. I'll update this.

**Comment by orangejulius** [comment]
Ok I've swapped the mappings for `locality` and `localadmin`, and updated the mega-comment above. I think it makes more sense now although the dividing line between `locality` and `localadmin` is still a bit blurry.

**Comment by trescube** [comment]
Late to the party but this seems pretty legit to me.

**Pull request merged**
