### PR TITLE
Configurable Geonames download URL

### PR DESCRIPTION
**Pull request by tiranno**
Takes care of  https://github.com/pelias/geonames/issues/239

The `download` function can now take a custom url - defined in the config file as `imports.geonames.sourceURL` from which to download a file. If `sourceURL` is undefined or an empty string the code defaults to the official Geonames dumps. The defined url can be a "template literal" format where `${countryCode}` will be evaluated with the given `countryCode`.

Other changes (let me know if these should be broken out to other PRs or tossed entirely): 
* moved `bin/download_data.js` main code out to lib/task/download.js to match template of other files
* renamed `bin/download_data.js` to `bin/downloadData.js` to match camelCase format of other files

### CODE REVIEW

**Comment by orangejulius** [comment]
Hey @tiranno,
Thanks for this PR. It looks great. My only suggestion would be to avoid the use of `eval()`. We don't really need _that_ much flexibility here, and `eval()` opens up all sorts of possible issues.

Having the config variable be a string which is a URL prefix which is concatenated with the country code to generate the full URL should be enough.

**Comment by tiranno** [comment]
So you're thinking something like `'http://example.com/' + countryCode + '.zip'`?

**Comment by orangejulius** [comment]
Yup, that would be perfect

**Comment by orangejulius** [comment]
Just tested and this works perfectly. thanks!!

**Pull request merged**
