### PR TITLE
Integrate pelias-admin-lookup (#18).

### LINKED ISSUE #18: integrate pelias-admin-lookup
Integrate the new `admin-lookup` to add administrative region names that are consistent with the other datasets we import.

relates to pelias/pelias#55

### PR DESCRIPTION
**Pull request by sevko**
Add the `pelias-admin-lookup` stream to the importer (even though Geonames already provides admin values), to ensure consistent naming across our datasets.

fixes #18
fixes pelias/pelias#55

### CODE REVIEW

**Comment by sevko** [comment]
We'll want to run an import with this in dev and figure out whether the difference in import time (which might be significant due to lookup slowness) is worth consistent data, which appears to be the only benefit here.

**Comment by dianashk** [comment]
fixes #18

**Comment by sevko** [comment]
Spot-checked geonames in the latest dev import, and [everything looks fine](http://pelias.dev.mapzen.com/search?input=a&zoom=6&layers=geoname) for a sample query. Copying over the results for posterity:

```javascript
{
    "bbox": [
        -112.12138,
        29.79355,
        -81.53482,
        45.5927
    ],
    "date": 1425933971938,
    "features": [
        {
            "geometry": {
                "coordinates": [
                    -106.2134,
                    33.60786
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "New Mexico",
                "admin2": "Lincoln",
                "alpha3": "USA",
                "id": "5454029",
                "layer": "geoname",
                "name": "A A A Tank",
                "text": "A A A Tank, Lincoln, New Mexico",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -106.10759,
                    33.52555
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "New Mexico",
                "admin2": "Lincoln",
                "alpha3": "USA",
                "id": "5454028",
                "layer": "geoname",
                "name": "A A A Tank",
                "text": "A A A Tank, Lincoln, New Mexico",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -86.68499,
                    30.76049
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Florida",
                "admin2": "Okaloosa",
                "alpha3": "USA",
                "id": "4145526",
                "layer": "geoname",
                "name": "A A Hilton Pond",
                "text": "A A Hilton Pond, Okaloosa, Florida",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -106.47503,
                    41.16164
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Wyoming",
                "admin2": "Carbon",
                "alpha3": "USA",
                "id": "5816768",
                "layer": "geoname",
                "name": "A Bar A Ranch",
                "text": "A Bar A Ranch, Carbon, Wyoming",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -106.56055,
                    41.16265
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Wyoming",
                "admin2": "Carbon",
                "alpha3": "USA",
                "id": "5816779",
                "layer": "geoname",
                "name": "A-A Ranch Airport",
                "text": "A-A Ranch Airport, Carbon, Wyoming",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -99.25449,
                    29.79355
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Texas",
                "admin2": "Bandera",
                "alpha3": "USA",
                "id": "4669525",
                "layer": "geoname",
                "name": "A Bar A Ranch",
                "text": "A Bar A Ranch, Bandera, Texas",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -81.53482,
                    36.0068
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "North Carolina",
                "admin2": "Caldwell",
                "alpha3": "USA",
                "id": "4452097",
                "layer": "geoname",
                "name": "A A Rauchfuss Lake",
                "text": "A A Rauchfuss Lake, Caldwell, North Carolina",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -98.86701,
                    32.90012
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Texas",
                "admin2": "Stephens",
                "alpha3": "USA",
                "id": "4669521",
                "layer": "geoname",
                "name": "A A Atkins Reservoir",
                "text": "A A Atkins Reservoir, Stephens, Texas",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -112.12138,
                    45.5927
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Montana",
                "admin2": "Madison",
                "alpha3": "USA",
                "id": "5636454",
                "layer": "geoname",
                "name": "A P A Mountain",
                "text": "A P A Mountain, Madison, Montana",
                "type": "geoname"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    -107.77367,
                    38.48499
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "Colorado",
                "admin2": "Montrose",
                "alpha3": "USA",
                "id": "5411264",
                "layer": "geoname",
                "name": "A B A Lateral",
                "text": "A B A Lateral, Montrose, Colorado",
                "type": "geoname"
            },
            "type": "Feature"
        }
    ],
    "type": "FeatureCollection"
}
```

**Comment by dianashk** [comment]
+1

**Pull request merged**
