### PR TITLE
Unignore files in data and metadata

### LINKED ISSUE #104: data folder is missing when installing as dependency
I use npm 3.10.5. When I install package via npm, the "data" folder is missing, and I get errors when running package. It's probably npm glitch, so maybe to fix you could rename this folder.

### PR DESCRIPTION
**Pull request by sheerun**
fixes #104

### CODE REVIEW

**Comment by orangejulius** [comment]
Hey @sheerun,
I edited your message a bit, Github doesn't link issues and PRs if the issue number is mentioned in the commit/pull request subject, only the body.


Thanks for the catch, I think this change makes sense. It also looks like we should better separate data files that are stored in git and those that are downloaded when the NPM `postinstall` lifecycle event fires.

**Comment by sheerun** [comment]
+1 for separation

**Comment by orangejulius** [comment]
Cool, we'll tackle that as a separate PR at some point. Also thanks for the tip on using `!entry` to negate a previous line in `.gitignore`. I didn't know that one.

**Comment by orangejulius** [comment]
Oh and LGTM!

**Comment by trescube** [comment]
:shipit:

**Pull request merged**
